### ISSUE TITLE
 Remove Unused Dependencies from Project

### ISSUE THREAD

**Issue by aryanp-86** [kuldeepaher01/hhg-erp#7]
**Issue: Remove Unused Dependencies from Project**

**Describe the issue**  
The project currently includes several dependencies that are no longer being used in the codebase. These unnecessary packages increase the size of the project, slow down builds, and add potential security risks.

**Expected behavior**  
Remove all unused dependencies to streamline the project, reduce build times, and minimize security vulnerabilities.

**Steps to resolve**  
1. Audit the current dependencies to identify which are no longer being used.
2. Remove the unused dependencies from `package.json`.
3. Run `pnpm install` to update the lock file.
4. Test the application to ensure functionality remains intact after the cleanup.

**Additional context**  
Cleaning up these dependencies will improve maintainability and make the project lighter and more secure.

**Comment by SandipGyawali** [comment]
@aryanp-86 can i look it ??
will update now.

**Comment by aryanp-86** [comment]
@SandipGyawali Ok, go for it👍

**Comment by SandipGyawali** [comment]
@aryanp-86 #9
